### ISSUE TITLE
New official SonarQube image with user and group 1000 

### ISSUE THREAD

**Issue by p0bailey** [Oteemo/charts#107]
Sonar has rolled out a new image for 8.3 with a change in user and group from 999 to 1000.

https://github.com/SonarSource/docker-sonarqube/blob/master/8/developer/Dockerfile#L96

And from the chart I can see that is it possible to adjust this value from 

https://github.com/Oteemo/charts/blob/master/charts/sonarqube/values.yaml#L19

However there's a bit in the deployment that has a reference to 999.

https://github.com/Oteemo/charts/blob/master/charts/sonarqube/templates/deployment.yaml#L58

Would be that be changed accordingly?

Best regards.

**Comment by namloc2001** [comment]
@p0bailey I think this is resolved in the latest version of the chart now.
```
# Set security context for sonarqube pod
securityContext:
  fsGroup: 1000

# Set security context for sonarqube container
containerSecurityContext:
  # Sonarqube dockerfile creates sonarqube user as UID and GID 1000
  runAsUser: 1000

```
