### ISSUE TITLE
[Nexus] npm proxy repo fails on client (Content-Length with chunked encoding mixed)

### ISSUE THREAD

**Issue by ThYpHo0n** [Oteemo/charts#108]
I run the recommended setup of the Nexus Helm chart on GKE.
```
...
ingress:
  enabled: true
  path: /*
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: my-static-ip
  tls:
    enabled: true
    secretName: wildcard-cert
nexusProxy:
  env:
    nexusHttpHost: nexus.company.com
    nexusDockerHost: containers.company.com
    enforceHttps: true
...
```
Nexus is reachable and runs fine. I configured Nexus to proxy the npm registry and I get the following issue:
`
 ERROR  request to https://nexus.company.com/repository/npm-public/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz failed, reason: Parse Error: Content-Length can't be present with chunked encoding
`
It seems that in the HTTP Headers both Content-Length and chunked encoding is present which violates the http standard.
I'm not entirely sure if this is the fault of the gce lb or nexus but since gce is the recommended setting I wanted to at least make you guys aware of this. I don't have a working solution yet. Will update this issue when I found it.
