### ISSUE TITLE
SSL connection on external Postgres

### ISSUE THREAD

**Issue by cosminoprea95** [Oteemo/charts#112]
There is no way to connect to an external ssl enabled Postgres database

**Comment by amit-k-yadav** [comment]
I have been looking for this option too. I think modifying the Helm chart locally is the only option.

**Comment by cosminoprea95** [comment]
I mame this work with some workaround without modifying the chart

Amit Yadav <notifications@github.com> schrieb am Di. 18. Aug. 2020 um 15:04:

**Comment by amit-k-yadav** [comment]
@cosminoprea95 please share that here? That would be super helpful 🙏
Thanks in advance!

**Comment by cosminoprea95** [comment]
I’ll get home in 20 mins and I’ll give you


Amit Yadav <notifications@github.com> schrieb am Di. 18. Aug. 2020 um 15:44:

**Comment by amit-k-yadav** [comment]
Sure. Whenever you get time. Thanks.

**Comment by cosminoprea95** [comment]
Ok, so basically you just put in the url connection you use the question
mark and the ssl configuration after it. Like:

You should add the following to the URL:

jdbc:postgresql://xx.xxx.xxx.xxx/sonarqube?ssl=true&sslmode=verify-ca&sslrootcert=/path/to/server-ca.pem&sslkey=/path/to/client-key.pem&sslcert=/path/to/client-cert.pem

See the documentation for the available SSL connection parameters
<https://jdbc.postgresql.org/documentation/head/connect.html#ssl> and SSL
client configuration
<https://jdbc.postgresql.org/documentation/head/ssl-client.html>.

Amit Yadav <notifications@github.com> schrieb am Di. 18. Aug. 2020 um 16:31:

**Comment by amit-k-yadav** [comment]
Thanks, I understand this part. I am not sure about `/path/to/server-ca.pem` and other certs mentioned in the JDBC URL. 

How did you get these inside the container with correct permissions?

**Comment by cosminoprea95** [comment]
You Mount them as secrets and just specify the path to the file in the url

Amit Yadav <notifications@github.com> schrieb am Di. 18. Aug. 2020 um 18:33:

**Comment by amit-k-yadav** [comment]
Actually, I have done this too. By using the following values file:

```yaml
...
  ## Specify extra volumes. Refer to ".spec.volumes" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  volumes:
    - name: certs-volume
      secret:
         secretName: certs-secret
    
  ## Specify extra mounts. Refer to ".spec.containers.volumeMounts" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  mounts:
    - name: certs-volume
      mountPath: /tmp/certs
...
```

I can even see the created directories and certificates are also mounted correctly. I specified paths to these certificates in JDBC URL but I got `permission denied` error.

Did you mount the secret the same way? If yes, how did you handle the permission issues?
