### ISSUE TITLE
[sonatype-nexus] Values.config.data sample

### ISSUE THREAD

**Issue by mdarii** [Oteemo/charts#133]
Hello,

I see that chart creates and mount an configmap, using data supplied using Values.config.data, do you have any sample of data structure of this field, also what is purpose of this field?

Thank you in advice

**Comment by zxkane** [comment]
Please add docs/links how using `config.data` and `additionalConfigMaps` to creating blobstores and repositories.

And does it mean that the nexus data will be readonly if specifying the `config.data` and `additionalConfigMaps`?

**Comment by weirdbiz** [comment]
As I look through templates and tested myself on minikube, `config.data` should contain configuration files in ConfigMap format. Example:
```
config:
  enabled: true
  data:
    nexus.properties: |
      # Jetty section
      # application-port=8081
      # application-host=0.0.0.0
      # nexus-args=${jetty.etc}/jetty.xml,${jetty.etc}/jetty-http.xml,${jetty.etc}/jetty-requestlog.xml
      # nexus-context-path=/${NEXUS_CONTEXT}

      # Nexus section
      # nexus-edition=nexus-pro-edition
      # nexus-features=\
      #  nexus-pro-feature

      # nexus.hazelcast.discovery.isEnabled=true

      # --- Example of additional config options. ---
      nexus.scripts.allowCreation=true
```

But there are some problems, that I had to workaround:

1. If you leave `values.yml` just as described above, your new file `nexus.properties` will be mounted at `/sonatype-nexus-conf` directory, which is default value from the Chart. It's not symlinked with `$data-dir/etc` directory.  So your Nexus3 instance will still use default `nexus.properties` configuration file from this folder without respect to your `config.data`.
2. If you add `config.mountPath` parameter with the value of `/nexus-data/etc` (that is `$data-dir/etc`) directory, you will get startup error: `java.nio.file.FileSystemException: /nexus-data/etc/logback: Read-only file system` because you mount the whole directory. And original `etc` folder contains at least subfolder `logback`, so your `mountPath` overrides it, causing startup failure.
3. I could have used mountPath's `subPath` k8s parameter to mount a single file, but it is not present in the provided Helm Chart. So I used that configuration values below in addition to `config.data`:
```
deployment:
  additionalVolumeMounts:
    - mountPath: /nexus-data/etc/nexus.properties
      subPath: nexus.properties
      name: sonatype-nexus-conf
```
After `helm upgrade` with pods restart, Nexus3 attached my new config file.
