### ISSUE TITLE
Getting 503 after installing in GKE with Private Ingress

### ISSUE THREAD

**Issue by btomasini** [Oteemo/charts#151]
After installing onto a GKE private cluster with a private ingress, I get the following error when I browse the site:

```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

The logs for the proxy container show:

```
2020-08-04 02:09:34,404 [ERROR] [vert.x-eventloop-thread-0] [io.vertx.core.net.impl.ConnectionBase] java.io.IOException: Connection reset by peer
```

Here is my spec:

``` yaml
releaseName: nexus
  chart:
    repository: https://oteemo.github.io/charts
    name: sonatype-nexus
    version: 2.5.0
  values:
    nexusProxy:
      env:
        nexusHttpHost: repo.auth.logic
        nexusDockerHost: docker.auth.logic

    nexusBackup:
      env:
        targetBucket: "gs://authlogic-nexus-backup"
      persistence:
        storageClass: standard

    nexus:
      service:
        type: ClusterIP
      annotations:
        cloud.google.com/neg: '{ "ingress": true }'

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        kubernetes.io/ingress.class: "gce-internal"
        kubernetes.io/ingress.allow-http: "false"
      tls:
        secretName: auth-logic-tls
      path: /*

    persistence:
      storageClass: standard
      storageSize: 200Gi

    resources:
      requests:
        cpu: 250m
        memory: 4800Mi
```
