### ISSUE TITLE
[sonarqube/stable] 8.4.2 - recommendations (kernel resources)

### ISSUE THREAD

**Issue by peppe77** [Oteemo/charts#177]
sonar-8.4.2 is out and has the following recommendations:

vm.max_map_ count is greater than or equal to 524288
fs.file-max is greater than or equal to 131072
the user running SonarQube can open at least 131072 file descriptors
the user running SonarQube can open at least 8192 threads

currently only the vm.max_map_count is supported by the init_container and has hard coded value to half of the recommended. The other ones are not currently supported in that init container. 

more info -> https://docs.sonarqube.org/latest/setup/upgrade-notes/

**Comment by namloc2001** [comment]
@peppe77 These values are set in values.yaml and then used via init-sysctl.yaml:
```
initSysctl:
  vmMaxMapCount: 524288
  fsFileMax: 131072
  nofile: 131072
  nproc: 8192
```
I believe this can therefore be closed.
