### ISSUE TITLE
Failed to Connect to external Postgres database

### ISSUE THREAD

**Issue by Shruti-R** [Oteemo/charts#210]
Hello,
I have postgres database setup on Azure and I am able to connect to it with psql. 
When I am setting below configurations in values.yaml, I am getting error "**Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').**"
 
**Values.yaml:**

```
jdbcUrlOverride: "jdbc:postgresql://<azure db server>:5432/<azure database>”
postgresql:
  enabled: false
  postgresqlServer:  "<azure db server>"
  postgresqlUsername: "<azure db user>@<azure db server>"
  postgresqlDatabase: "<azure database that is already created>"
  postgresqlPassword: "<azure database password>"

elasticsearch:
   configureNode: false
   bootstrapChecks: false

initSysctl:
  enabled: false
```

Are there any other configurations required for establishing connection? where can I see properties set for sonar.jdbc as mentioned in error?
