### ISSUE TITLE
[sonatype-nexus] unable to login to docker registry

### ISSUE THREAD

**Issue by esvirskiy** [Oteemo/charts#212]
Hi.

I am seeing the following error when trying to login to a hosted docker registry.

```nexus-sonatype-nexus-0 nexus-proxy 2020-11-11 15:44:32,001 [ERROR] [vert.x-eventloop-thread-0] [io.vertx.core.http.impl.HttpClientRequestImpl] io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5003```

I have a dedicated ingress configured for Docker:

```
ingressDocker:
  enabled: true
  labels: {}
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
  rules:
    - host: nexus-docker.domain.com
      http:
        paths:
          - backend:
              serviceName: nexus-sonatype-nexus
              servicePort: 8080
            path: /
  tls:
    enabled: true
    secretName: nexus-docker-tls
    hosts:
      -  nexus-docker.domain.com
```

I noticed the docker port is set to 5003 and enabled by default at https://github.com/Oteemo/charts/blob/master/charts/sonatype-nexus/values.yaml#L47 but the container is not listening for it...

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:41935         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      -
```

Any help is appreciated.
