### ISSUE TITLE
[Nexus] - additionalConfigMaps doesnt' work

### ISSUE THREAD

**Issue by fjvela** [Oteemo/charts#231]
Hello,

I deployed the last version of the chart and I enable additionalConfigMaps

```
additionalConfigMaps:
  - name: my-maven
    labels:
      nexus-type: repository
    data:
      recipe: 'MavenProxy'
      remoteUrl: 'https://repo.maven.apache.org/maven2/'
      blobStoreName: 'az-blob-storage-java'
      strictContentTypeValidation: 'true'
      versionPolicy: 'RELEASE'
      layoutPolicy: 'STRICT'
```

The configmap has beed deployed but nexus doesn't load it. 

Is additionalConfigMaps  working?
