### ISSUE TITLE
SonarQube - How do I increase the JVM Compute Engine (sonar.ce.javaOpts) heap size

### ISSUE THREAD

**Issue by bevank** [Oteemo/charts#246]
Hi 

Might be a silly question but I am trying to test Sonarqube in Kubernetes and need to increase the JVM Compute Engine (sonar.ce.javaOpts) heap size as we have projects that require more memory for processing 

Trying to increase the heap size using helm and don't seem to be able to get it to increase - can someone please let me know if there is a how-to or wiki I can follow to set the sonar.ce.javaOpts option in the helm chart 

Thanks

**Comment by gvrf2911** [comment]
Hi,

I hope I am not answering too late, I am using this in my ``values.yml``:
``` yaml
sonarProperties:
  sonar.web.javaOpts: -Xms...
  sonar.ce.javaOpts: -Xms...
```
