### ISSUE TITLE
Docker Port in Nexus Proxy not created

### ISSUE THREAD

**Issue by guilhermesenazuza** [Oteemo/charts#249]
https://github.com/Oteemo/charts/blob/be2d446e64ffb02864825c091b2dba55af6261ad/charts/sonatype-nexus/templates/proxy-svc.yaml#L44

The current template define the lines above in the proxy-svc.yaml:
```yaml
{{- if .Values.nexusProxy.enabled }}
      targetPort: {{ .Values.nexusProxy.targetPort }}
{{- else }}
      targetPort: {{ .Values.nexus.nexusPort }}
    - port: {{ .Values.nexus.dockerPort }}
      name: docker
      protocol: TCP
      targetPort: {{ .Values.nexus.dockerPort }}
{{- end }}
```
Considering the condition .Values.nexusProxy.enabled true, shouldn't the docker port also be added to the nexusProxy service like above?

```yaml
{{- if .Values.nexusProxy.enabled }}
      targetPort: {{ .Values.nexusProxy.targetPort }}
{{- else }}
      targetPort: {{ .Values.nexus.nexusPort }}
{{- end }}
    - port: {{ .Values.nexus.dockerPort }}
      name: docker
      protocol: TCP
      targetPort: {{ .Values.nexus.dockerPort }}
```
