### ISSUE TITLE
Sonarqube - Postgresql uses Hardcoded password instead of randomly generated 

### ISSUE THREAD

**Issue by Homopatrol** [Oteemo/charts#293]
The Postgresql password is being hard coded in [values.yaml](https://github.com/Oteemo/charts/blob/master/charts/sonarqube/values.yaml#L277), it is not good practice to hardcode default credentials in Helm charts especially when the Postgresql chart contains a random-generate function to create passwords. 
```
postgresql:
...
  postgresqlUsername: "sonarUser"
  postgresqlPassword: "sonarPass"
  postgresqlDatabase: "sonarDB"
```

 this is not good practice to use a fixed password, especially when the rando-generate function is already in the chart

**Version of Helm and Kubernetes**

Helm v3.5.2
Kubernetes 1.19.0
