### ISSUE TITLE
no matches for kind "Ingress" in version "networking.k8s.io/v1

### ISSUE THREAD

**Issue by patsevanton** [Oteemo/charts#311]
Hello. I try install sonatype-nexus to kubernetes 1.18

Add repo
```
helm repo add oteemocharts https://oteemo.github.io/charts
```

Install sonatype-nexus
```
helm install -f my-values.yaml sonatype-nexus oteemocharts/sonatype-nexus
```

File my-values.yaml:
```
nexusProxy:
  env:
    nexusHttpHost: my-dns-name.sslip.io

ingress:
  enabled: true
```

Get error
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```
