### ISSUE TITLE
unable to upgrade sonarqube helm chart to version 9.8.2

### ISSUE THREAD

**Issue by QualoZe0t** [Oteemo/charts#314]
Hi,

I am using helm chart version chart: sonarqube-9.6.3 but i am facing issue with upgrade to version 9.8.2 .. Concretely having issue with validation ( see below ) . Can you please help me what was chaneged in template's ?

```
helm upgrade --create-namespace --atomic -i --version 9.8.2 -n sonarqube -f sonarqube/values.yaml sonarqube oteemocharts/sonarqube

Error: UPGRADE FAILED: error validating "": error validating data: unknown object type "nil" in Secret.data.postgresql-password
```

I am using external secret which are working properly on version 9.6.3
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: naming_of_secrets
  namespace: sonarqube
spec:
  backendType: secretsManager
  data:
    - key: bla
      name: postgresqlUsername
      property: postgresqlUsername
    - key: bla
      name: postgresqlPassword
      property: postgresqlPassword
```

**Comment by muffl0n** [comment]
I have a similar issue. After upgrading from 9.6.4 to 9.8.2, I get a change for the password-secret on every run:
``` 
# Source: sonarqube/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sonarqube
    chart: sonarqube-9.8.2
    heritage: Helm
    release: sonarqube
  name: sonar-postgresql
data:
-   postgresql-password: '-------- # (9 bytes)'
+   postgresql-password: '++++++++ # (16 bytes)'
type: Opaque
```
My values.yaml just activates the ingress
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "acme-issuer"

  hosts:
    - name: sonarqube.foo.bar
      ...
```
