### ISSUE TITLE
Sonarqube broken template when using ingress

### ISSUE THREAD

**Issue by sashokbg** [Oteemo/charts#324]
This is a **bug report**

**How to reproduce:**
`helm template -f sonar-gke/files/helm_values.yaml wb-sonar oteemocharts/sonarqube`

**What works:**
 `helm template -f sonar-gke/files/helm_values.yaml wb-sonar oteemocharts/sonarqube --version 9.4.1`
It looks like the problem was introduced in 9.5.0

**Error message:**

> 
> Error: template: sonarqube/templates/ingress.yaml:31:41: executing "sonarqube/templates/ingress.yaml" at <.serviceName>: can't evaluate field serviceName in type interface {}
> 
> Use --debug flag to render out invalid YAML

**Values**

```
replicaCount: 1

image:
  tag: latest

ingress:
  enabled: true
  hosts:
    - name: "sonar.mydomain.com"
      path: "/*"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "sonar-global-address"

postgresql:
  enabled: true
  postgresqlUsername: "sonar"
  postgresqlPassword: "pass"
  postgresqlDatabase: "db"
  service:
    port: 5432

```
