### ISSUE TITLE
service account name only used if serviceAccount.create = true

### ISSUE THREAD

**Issue by michbeck100** [Oteemo/charts#327]
Given this values.yaml:

```yaml
serviceAccount:
  create: false
  name: my-custom-account
```

The deployment is still using the release name, because the name is only used if serviceAccount.create is true: https://github.com/Oteemo/charts/blob/master/charts/sonarqube/templates/deployment.yaml#L48
