### ISSUE TITLE
[SonarQube] Ingress error "wrong type for value"

### ISSUE THREAD

**Issue by victtsl** [Oteemo/charts#339]
For sonarqube chart, there is an error 

**How to reproduce**
`helm template my-sonar . -f values.yaml`

**Error message:**
```
Error: template: sonarqube/templates/ingress.yaml:34:63: executing "sonarqube/templates/ingress.yaml" at <$value>: wrong type for value; expected string; got bool

Use --debug flag to render out invalid YAML
```

**Values:**
```
replicaCount: 1

image:
  repository: sonarqube
  tag: 8.9.7-community
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - name: sonar.organization.com
      path: /
      pathType: Prefix
  annotations: 
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/force-ssl-redirect: true
    nginx.ingress.kubernetes.io/proxy-body-size: '0'

postgresql:
  enabled: false
```
