### ISSUE TITLE
chart/sonarqube - support for SSL

### ISSUE THREAD

**Issue by rnkhouse** [Oteemo/charts#36]
This is my current `values.yaml` file:

    ingress:
    enabled: true
    # Used to create an Ingress record.
    hosts:
      - name: sonar.example.com
        # default paths for "/" and "/*" will be added
        path: /
        # If a different path is defined, that path and {path}/* will be added to the ingress resource
        # path: /sonarqube
        tls: true
        tlsHosts:
        - sonar.example.com
        tlsSecret: example-tls
    annotations:
        kubernetes.io/ingress.class: nginx-internal
        #kubernetes.io/tls-acme: "true"
        #This property allows for reports up to a certain size to be uploaded to SonarQube
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"

But, TLS is not working. Portal is running on port 80.

**Comment by rjkernick** [comment]
Should be something like 
```
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: sonar.example.com
      # default paths for "/" and "/*" will be added
      path: /
      # If a different path is defined, that path and {path}/* will be added to the ingress resource
      # path: /sonarqube
      tls: true
      tlsHosts:
      - sonar.example.com
      tlsSecret: example-tls
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    #kubernetes.io/tls-acme: "true"
    #This property allows for reports up to a certain size to be uploaded to SonarQube
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
```

I think your indentation was off
