### ISSUE TITLE
[nexus] Missing Service Type in values.yaml

### ISSUE THREAD

**Issue by dmpe** [Oteemo/charts#40]
```
  type: {{ .Values.service.serviceType }}
```

is missing in `values.yaml`. Therefore when using "helm render" you get `type:    ` which would be undesirable.

```
# # To use an additional service, set enable to true
service:
  # name: additional-svc
  enabled: false
  labels: {}
  annotations: {}
  ports:
  - name: nexus-service
    targetPort: 80
    port: 80
```
