### ISSUE TITLE
[sonarqube] Duplicate scheduling settings in deployment.yaml template

### ISSUE THREAD

**Issue by rustymunkey** [Oteemo/charts#45]
Hi!

First of all: Thanks for taking on the sonarqube chart!

I posted an issue in the old helm repository about the duplicate scheduling settings in the templates/deployment.yaml: https://github.com/helm/charts/issues/19713
The issue still persists, so i would like to repeat it here, with updated line information.

**Describe the bug**
The deployment.yaml file contains duplicate entries of the elements `nodeSelector`, `hostAliases`, `tolerations` and `affinity`. The problem is that the [first occurence](https://github.com/Oteemo/charts/blob/master/charts/sonarqube/templates/deployment.yaml#L124-L139) between L124 and L139 of these elements is right in the middle of the `initContainer` array.

This leads to a failed helm install when using for example affinity and the plugin install init container. 

As the elements in question have their correct occurence between L262 and L273 it should be save to simply remove the first, incorrect ones.

A workaround is to remove the node scheduling settings from the values.yaml.

**Which chart**:
stable/sonarqube 3.2.7

**What happened**:
When using affinity and the plugin install init container, the chart installation fails with the message:

> Failed to install app sonarqube. Error: YAML parse error on sonarqube/templates/deployment.yaml: error converting YAML to JSON: yaml: line 97: did not find expected key

Line 97 in my case was the duplicate entry of `affinity`

**How to reproduce it** (as minimally and precisely as possible):
I used the following values (among others):
```
  plugins:
    install:
      - "https://github.com/SonarSource/sonar-ldap/releases/download/2.2-RC3/sonar-ldap-plugin-2.2.0.601.jar"
  
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
          - key: "node-role"
            operator: In
            values:
            - services
```
