### ISSUE TITLE
sonatype-nexus deploymentStrategy expects string

### ISSUE THREAD

**Issue by gmihovics** [Oteemo/charts#77]
RollingUpdate deadlock on the persistent volume claim for nexus deployments so I went to change the `deploymentStrategy` to **Recreate** but this generates an invalid spec template. 

**templates/deployment-statefulset.yaml**
```
strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
{{- end }}
```
This is wrong since strategy should actually be

```
strategy:
  type: <type>
```

You can replicate this by setting `deploymentStrategy` to either **RollingUpdate** or **Recreate**.

**Comment by rjkernick** [comment]
This is the intended behavior because you could have other items for the strategy besides type. For instance: 

```
deploymentStrategy: 
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
```
