### ISSUE TITLE
[sonarqube] configuration of Ingress with two paths does not work with Traefik V2

### ISSUE THREAD

**Issue by gvrf2911** [Oteemo/charts#84]
Hi,

We use Traefick V2 as Ingress Controller and the configuration of two paths gives a 404 error when we try to access to SonarQube.

These paths are defined in the ingress.yml file:
```yml
    {{- $path := default "/" .path }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ $path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          - path: {{ printf "%s/*" (trimSuffix "/" $path) }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
```
It works fine if we delete the second path.
We have this problem since we have migrated on the V2 of Traefik.

Anyway, is it possible to know why there is this double configuration of path?
Is it possible to remove it?

Thanks in advance.
