### ISSUE TITLE
[sonarqube] Sonarqube does not work with ingress

### ISSUE THREAD

**Issue by RomainWilbert** [Oteemo/charts#91]
Hi,

I installed Sonarqube chart with the following command:
helm install sonar stable/sonarqube --set persistence.enabled=true --set persistence.existingClaim=sonar --set ingress.annotations."kubernetes\.io/ingress\.class"=traefik --set ingress.hosts[0].path=/sonarqube --set ingress.enabled=true

I have a Traefik ingress. When i access the app through Traefik LB IP, I get 404 on resource loading:
http://IP/js/vendors-main.m.d184ed05.chunk.js
http://IP/js/main.m.115b48b2.js
It seems a configuration is missing somewhere for link generation :(

**Comment by RomainWilbert** [comment]
I tried following configuration with no success :
`--set livenessProbe.sonarWebContext=/sonarqube/ --set readinessProbe.sonarWebContext=/sonarqube/ --s`et jvmOpts="-Dsonar.web.context=/sonarqube"
Weird because java option is passed to the web process:
`Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/local/openjdk-11/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError **-Dsonar.web.context=/sonarqube** -Djava.security.egd=file:/dev/./urandom -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process11559071430994447086properties`

I also tried to create yaml file with following configuration but no success either:
`command: [ "-Dsonar.web.context=/sonarqube" ]`

**Comment by smartlizzard** [comment]
@RomainWilbert I am also facing same issue.

**Comment by RomainWilbert** [comment]
I found the solution but i don't have access to my computer until monday...stay tuned until then !! :)

**Comment by smartlizzard** [comment]
@RomainWilbert can you send me the file ?

**Comment by RomainWilbert** [comment]
```
readinessProbe:
  sonarWebContext: /sonar/
livenessProbe:
  sonarWebContext: /sonar/
persistence:
  enabled: true
  existingClaim: sonar
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - name:
      path: /sonar
env:
  - name: sonar.web.context
    value: /sonar
```

**Comment by gbonnefille** [comment]
If so, perhaps someone can propose an evolution of the chart, factorizing the context in a value?
Or close this issue.

**Comment by abdennour** [comment]
Hi , 

I have same issue : Sonar worked with `kubect port-forward` to localhost, however, it does not work behind my nginx ingress controller.

This is my helm release values : 

```yaml
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: sonar.devops.company.com
      path: /
    - name: sonar.company.com
      path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/service-upstream: "true"
```
Commented lines have been tried but no way.
