### ISSUE TITLE
[Nexus] Extra ingress for nexus-proxy

### ISSUE THREAD

**Issue by EvgeniGordeev** [Oteemo/charts#96]
### Scenario:

with given values.yml

```yaml
nexusProxy:
  env:
    nexusHttpHost: nexus.example.com
ingress:
    enabled: true
    rules:
      - host: nexus-extra.example.com
        http:
          paths:
            - backend:
                serviceName: <release_name>-sonatype-nexus
                servicePort: 8080
              path: /
```
It's impossible to access nexus by `nexus-extra.example.com`: 

This page is displayed - https://github.com/travelaudience/nexus-proxy/blob/master/src/main/resources/templates/invalid-host.hbs. 

### Expected Result
NXRM can be accessув by both host names - `nexus.example.com` and `nexus-extra.example.com`.

### Workaround
Use `nginx.ingress.kubernetes.io/upstream-vhost: nexus.example.com` in `ingress.annotations`. NB: docker repository won't work after `nginx.ingress.kubernetes.io/upstream-vhost` is set.

```yaml
nexusProxy:
  env:
    nexusHttpHost: nexus.example.com
ingress:
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: nexus.example.com
  enabled: true
  rules:
    - host: nexus-extra.example.com
       http:
         paths:
           - backend:
              serviceName: <release_name>-sonatype-nexus
              servicePort: 8080
              path: /
```

**Comment by rjkernick** [comment]
Want to add a section into the Readme for multiple host ingress?

**Comment by EvgeniGordeev** [comment]
@rjkernick I realized that this approach probably won't work if docker registry is used. Since hostname will be overridden and I suppose nexus-proxy distinguishes between the protocols based on that. 

```yaml
nexusProxy:
  env:
    nexusHttpHost: nexus.example.com
    nexusDockerHost: docker.example.com
```
I'll verify and update the description/PR accordingly.

**Comment by EvgeniGordeev** [comment]
@rjkernick Docker repository won't work if the workaround is used as is. A separate ingress must be added to add extra hostnames to the main UI.
```bash
Error response from daemon: login attempt to https://dockerhub.example.com/v2/ failed with status: 404 Not Found
```

My current approach is to use this chart as a subchart and add an extra ingress.

**Comment by Skaronator** [comment]
Any updates on this issue? I'd like to see an additional ingress as well. @EvgeniGordeev

**Comment by EvgeniGordeev** [comment]
@Skaronator Started working on PR. This will require a split of ingress into http ingress and docker registry ingress which would allow to provide any rules separately and support multiple hosts in both cases: 

```yaml
nexusProxy:
  env:
    nexusHttpHost: nexus.example.com
    nexusDockerHost: docker.example.com
ingress:
  enabled: true
  annotations:
    # workaround for https://github.com/helm/charts/issues/5385
    nginx.ingress.kubernetes.io/upstream-vhost: nexus.example.com
  rules:
    - host: nexus-extra.example.com
      http:
        paths:
          - backend:
              serviceName: nexus-sonatype-nexus
              servicePort: 8080
            path: /
ingressDocker:
  enabled: true
  annotations:
    # workaround for https://github.com/helm/charts/issues/5385
    nginx.ingress.kubernetes.io/upstream-vhost: docker.example.com
  rules:
    - host: docker-extra.example.com
      http:
        paths:
          - backend:
              serviceName: nexus-sonatype-nexus
              servicePort: 8080
            path: /
```
